### ISSUE TITLE
У вас получилось парсить номера более 10 раз подряд?

### ISSUE THREAD

**Issue by K3ler** [iKoles-dev/OlxPhoneParser#1]
Реализовал такую же штуку c помощью Selenium на Python. Тоже с эмуляцией мыши. Но более 10 объявлений идет бан от OLX.

**Comment by iKoles-dev** [comment]
Да, получилось парсить. Я также использую селениум для парсинга.

01.02.2020, Mikhail<notifications@github.com> написал(а):

**Comment by iKoles-dev** [comment]
В софт встроена поддержка best-proxies.ru - с ними всё работает прекрасно.
Да, пришлось немного покопаться, чтобы настроить селениум и прокси, но всё оказалось не так плохо, как пишут на форумах.
